jMathExpr-WEB/src/main/java/jmathexpr/web/controller/ExpressionsBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package jmathexpr.web.controller;

import java.io.Serializable;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import jmathexpr.util.context.ExpressionContext.Item;
import jmathexpr.util.context.Statement;

import jmathexpr.web.ejb.ExpressionServiceLocal;

/**
 * Backing bean for user inputs.
 * 
 * @author Elemér Furka
 */
@SessionScoped
@ManagedBean(name = "whiteboard")
public class ExpressionsBean implements Serializable {
    
    private String actual;
    
    @EJB
    private ExpressionServiceLocal service;

    public String getActual() {
        return actual;
    }

    public void setActual(String expression) {
        actual = expression;
        
        Statement statement = service.add(expression);
        
        service.execute(statement);
    }    

    public List<Item> getEntries() {
        return service.getContext().getFirstLevelItems();
    }
}

jMathExpr-WEB/src/main/webapp/expressions.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <f:view contentType="text/html">
        <h:head>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type"/>
                <title>jMathExpr</title>
            </f:facet>
            
            <script type="text/javascript"
            src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=AM_HTMLorMML" />
            
            <h:outputStylesheet name="style.css" library="css" />
        </h:head>

        <h:body>

            <p:layout fullPage="true">

                <p:layoutUnit position="north" size="100" resizable="true">
                    <h:form>
                        <p:outputLabel for="input" value="Expression: " />
                        <p:inputText id="input" value="#{whiteboard.actual}" />
                    </h:form>
                </p:layoutUnit>

                <p:layoutUnit position="south" size="100" closable="true" collapsible="true">
                    Footer
                </p:layoutUnit>

                <p:layoutUnit position="center">
                    <p:dataTable var="item" value="#{whiteboard.entries}" styleClass="whiteboard">
                        <p:column styleClass="command">
                            <h:outputText value="#{item.statement.command.toString()}"
                                          rendered="#{item.statement.command != Expression}"/>
                        </p:column>

                        <p:column styleClass="expressionEntry">
                            <h:outputText value="`#{item.statement.expression.toAsciiMath()}`" />
                        </p:column>
                        
                        <p:column styleClass="expressionId">
                            <h:outputText value="(#{item.id})" />
                        </p:column>
                    </p:dataTable>
                </p:layoutUnit>
            </p:layout>
        </h:body>
    </f:view>
</html>